enable test results

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -13,6 +13,8 @@ jobs:
     name: RustFmt Check
     runs-on: ubuntu-latest
     timeout-minutes: 45
+    permissions:
+      checks: write
     steps:
       - uses: actions/checkout@v4
 
@@ -34,6 +36,7 @@ jobs:
     permissions:
       contents: read
       packages: read
+      checks: write
     timeout-minutes: 45
     strategy:
       fail-fast: false
@@ -68,7 +71,15 @@ jobs:
         run: just clippy
 
       - name: Run tests
-        run: just test
+        run: just ci-test
+
+      - name: Test Reporter
+        uses: dorny/test-reporter@v1.9.0
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Test Results                   # Name of the check run which will be created
+          path: ./target/nextest/ci/junit.xml    # Path to test results
+          reporter: java-junit                 # Nextest generates JUnit XML
 
   docker:
     name: Create docker image
